version: "3"

services:
  syslog:
    image: balabit/syslog-ng:latest
    container_name: syslog
    network_mode: host

  app:
    image: asteroids:latest
    depends_on: 
      - syslog
    build: .
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
    network_mode: host
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      mode: replicated
      replicas: 2