# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import remote.asteroids_pb2 as asteroids__pb2


class AsteroidsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Discover = channel.unary_unary(
                '/Asteroids/Discover',
                request_serializer=asteroids__pb2.Peer.SerializeToString,
                response_deserializer=asteroids__pb2.Peer.FromString,
                )
        self.Xfer = channel.unary_unary(
                '/Asteroids/Xfer',
                request_serializer=asteroids__pb2.Outbound.SerializeToString,
                response_deserializer=asteroids__pb2.Success.FromString,
                )


class AsteroidsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Discover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Xfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AsteroidsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Discover': grpc.unary_unary_rpc_method_handler(
                    servicer.Discover,
                    request_deserializer=asteroids__pb2.Peer.FromString,
                    response_serializer=asteroids__pb2.Peer.SerializeToString,
            ),
            'Xfer': grpc.unary_unary_rpc_method_handler(
                    servicer.Xfer,
                    request_deserializer=asteroids__pb2.Outbound.FromString,
                    response_serializer=asteroids__pb2.Success.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Asteroids', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Asteroids(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Discover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Asteroids/Discover',
            asteroids__pb2.Peer.SerializeToString,
            asteroids__pb2.Peer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Xfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Asteroids/Xfer',
            asteroids__pb2.Outbound.SerializeToString,
            asteroids__pb2.Success.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
